[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "slae-test-suite"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"

dependencies = ["requests", "python-dotenv"]
